export interface IDataByCrType {
  avg_per_fuel_consumption: number,
  avg_per_uncharge_power: string,
  avg_velocity: number,
  car_count: number,
  car_type_id: number,
  car_type_name: string,
  end_fuel: number,
  end_mileage: number,
  mileage_source: number,
  start_fuel: number,
  start_mileage: number,
  total_can_points: number,
  total_charge_count: number,
  total_charge_power: number,
  total_fuel_consumption: number,
  total_mileage: number,
  total_offline_time: number,
  total_points: number,
  total_run_time: number,
  total_stop_time: number,
  total_uncharge_count: number,
  total_uncharge_power: number,
  total_work_days: number,
  total_work_time: number
}